/*PLEASE DO NOT EDIT THIS CODE*/
/*This code was generated using the UMPLE 1.31.1.5860.78bb27cc6 modeling language!*/

package cruise.umple.compiler.php;

// line 1 "../../../../../UmpleTLTemplates/association_GetMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_GetOne.ump"
// line 5 "../../../../../UmpleTLTemplates/association_Get_All.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddIndexControlFunctions.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddMNToMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddMNToOnlyOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddMNToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddMStarToMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddMandatoryManyToOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddManyToManyMethod.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddManyToOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddManyToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddOptionalNToOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddOptionalNToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddUnidirectionalMN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddUnidirectionalMStar.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddUnidirectionalMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_AddUnidirectionalOptionalN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_IsNumberOfValidMethod.ump"
// line 1 "../../../../../UmpleTLTemplates/association_MaximumNumberOfMethod.ump"
// line 1 "../../../../../UmpleTLTemplates/association_MinimumNumberOfMethod.ump"
// line 1 "../../../../../UmpleTLTemplates/association_RemoveMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_RequiredNumberOfMethod.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetMNToMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_GetPrivate.ump"
// line 4 "../../../../../UmpleTLTemplates/association_SetMNToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetMStarToMany.ump"
// line 4 "../../../../../UmpleTLTemplates/association_SetNToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOneToAtMostN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOneToMandatoryMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOneToMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOneToManyAssociationClass.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOneToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalNToMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalOneToMandatoryMN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalOneToMandatoryMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalOneToMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalOneToOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalOneToOptionalN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetOptionalOneToOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalMN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalMStar.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalMany.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalOptionalN.ump"
// line 1 "../../../../../UmpleTLTemplates/association_SetUnidirectionalOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/association_Sort.ump"
// line 47 "../../../../../UmpleTLTemplates/association_Set_All.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_Get.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetCodeInjection.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetDefaulted.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetDefaultedCodeInjection.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetDerived.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetDerivedCodeInjection.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetMany.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetManySubclass.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetUnique.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetUniqueCodeInjection.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_HasUnique.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_HasUniqueCodeInjection.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_GetSubclass.ump"
// line 18 "../../../../../UmpleTLTemplates/attribute_Get_All.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_IsBoolean.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_IsBooleanCodeInjection.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_IsBooleanCodeInjectionDerived.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_IsBooleanDerived.ump"
// line 7 "../../../../../UmpleTLTemplates/attribute_IsBoolean_All.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_Set.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_SetDefaulted.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_SetDefaulted_subclass.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_SetImmutable.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_SetMany.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_SetMany_subclass.ump"
// line 1 "../../../../../UmpleTLTemplates/attribute_Set_subclass.ump"
// line 10 "../../../../../UmpleTLTemplates/attribute_Set_All.ump"
// line 1 "../../../../../UmpleTLTemplates/class_MethodDeclaration.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignImmutableOptionalMany.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignImmutableOptionalN.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignImmutableOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignOne.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignOneToOne.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignOptionalMany.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignUndirectionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssignImmutable.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeUnassignedImmutable.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_NestedStateMachineAssignDefault.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_Singleton.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_StateMachineAssignDefault.ump"
// line 23 "../../../../../UmpleTLTemplates/constructor_DeclareDefault.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationAssignMandatoryMany.ump"
// line 4 "../../../../../UmpleTLTemplates/constructor_AssociationAssignDefault.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AssociationCreateOneToOne.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssign.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssignAutounique.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssignUnique.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssignDefaulted.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssignLazy.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_AttributeAssignList.ump"
// line 1 "../../../../../UmpleTLTemplates/constructor_CallParentConstructor.ump"
// line 12 "../../../../../UmpleTLTemplates/constructor_DeclareOneToOne.ump"
// line 5 "../../../../../UmpleTLTemplates/constructor_Declare_All.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_MandatoryFromOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_ManyFromMN.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_ManyFromMany.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_ManyFromOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_ManyFromOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_ManyFromX_comp.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OneFromMany.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OneFromOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OneFromOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromMN.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromMN_comp.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromMany.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromMany_comp.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromN.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromOne_comp.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_OptionalOneFromOptionalOne.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_UndirectionalMany.ump"
// line 1 "../../../../../UmpleTLTemplates/delete_UndirectionalOne.ump"
// line 22 "../../../../../UmpleTLTemplates/delete_All.ump"
// line 1 "../../../../../UmpleTLTemplates/equals.ump"
// line 1 "../../../../../UmpleTLTemplates/equals_default.ump"
// line 1 "../../../../../UmpleTLTemplates/members_AllAssociations.ump"
// line 1 "../../../../../UmpleTLTemplates/members_AllAttributes.ump"
// line 1 "../../../../../UmpleTLTemplates/members_AllDoActivities.ump"
// line 1 "../../../../../UmpleTLTemplates/members_AllHelpers.ump"
// line 1 "../../../../../UmpleTLTemplates/members_AllStateMachines.ump"
// line 1 "../../../../../UmpleTLTemplates/members_AllStatics.ump"
// line 1 "../../../../../UmpleTLTemplates/state_machine_Event.ump"
// line 4 "../../../../../UmpleTLTemplates/state_machine_Events_All.ump"
// line 1 "../../../../../UmpleTLTemplates/state_machine_Get.ump"
// line 1 "../../../../../UmpleTLTemplates/state_machine_GetFull.ump"
// line 5 "../../../../../UmpleTLTemplates/state_machine_Get_All.ump"
// line 1 "../../../../../UmpleTLTemplates/state_machine_Set.ump"
// line 1 "../../../../../UmpleTLTemplates/state_machine_SetSimple.ump"
// line 5 "../../../../../UmpleTLTemplates/state_machine_Set_All.ump"
// line 1 "../../../../../UmpleTLTemplates/trace.ump"
// line 1 "../../../../../UmpleTLTemplates/UmpleNotice.ump"
// line 1 "../../../../../UmpleTLTemplates/interface_AbstractMethodDeclaration.ump"
// line 1 "../../../../../UmpleTLTemplates/interface_constantDeclaration.ump"
public class UmpleToPhp
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //------------------------
  // CONSTRUCTOR
  //------------------------

  public UmpleToPhp()
  {}

  //------------------------
  // INTERFACE
  //------------------------

  public void delete()
  {}

}